spring:
  config:
    import: optional:configserver:http://localhost:8080
  application:
    name: service-harmony

#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate:  DEBUG